### ISSUE TITLE
Urlresolver update failed 

### ISSUE THREAD

**Issue by donsai007** [Eldorados/script.module.urlresolver#319] opened 2015-09-04 19:47 UTC
Hello sir CAN Anyone help me my urlresolver addon can be updted i am on latest Kodi isengarrd . Everytime i havé a message That urlresolver update failed

Thank you guys

**Comment by Eldorados** [comment] 2015-09-22 13:28
Try deleting your addons.db file

Closing this as the issue is not directly related to urlresolver, it's a Kodi addon update issue

**Closed by Eldorados** 2015-09-22 13:28 UTC
