### ISSUE TITLE
Bad performance instantiating HostMediaFile()

### ISSUE THREAD

**Issue by tknorris** [Eldorados/script.module.urlresolver#181] opened 2014-07-01 20:25 UTC
Hey Eldorado, several users have reported poor performance on slower hardware when using the 1CH addon w/ source dialogs. I tracked part of the problem down to when instantiating HostedMediaFile() objects they are validated against the resolver impls. On slower hardware (e.g. the rpi) this is ends up being a very expensive operation. Unfortunately, choose_source requires a HostedMediaFile list. Anything you can do here to improve it? Maybe delay the validation until a source in chosen? Maybe an optional param to __init__ to skip the validation? If there is nothing you can do, I can replace the 1CH urlresolver.choose_source() call with a custom one that uses 1CH hoster items but doesn't do validation at all. Let me know your thoughts.

**Comment by VioletRed** [comment] 2015-01-12 08:55
> Unfortunately, choose_source requires a HostedMediaFile list. Anything you can do here to improve it?

This is getting a bit frustrating for me. I have seen complains about 1channel and other URLResolver-dependent plugins since [at least 2012](http://forum.osmc.tv/showthread.php?tid=4237),

**Comment by tknorris** [comment] 2015-01-12 17:00
I think the problem is your changes are too extensive to be all understood and tested at once. Several addons use urlresolver and it would be very bad to break it in unexpected ways.

**Comment by tknorris** [comment] 2015-01-12 17:28
Also, speaking only for myself, I still don't agree w/ your PR. I think the same thing can be achieved more simply by making valid_url a class method and making smaller changes to how the Manager loads the resolvers such that it only instantiates ones that need one of the other methods to be called.

In addition, your current PR depends on EVERYONE writing resolvers to know that they need to do them differently now to account for the domain check. To me, that's also a problem.

**Comment by Eldorados** [comment] 2015-01-12 18:16
Note that in 2012 raspberry devices were running XBMC considerably slower than they do today, but at the same time URLResolver has increased it's number of resolvers by a large amount. The issue is really only becoming apparent as urlresolver grows

I haven't had enough time to thoroughly go over the PR due to the amount of changes and due to limited time.. this isn't a change that I want to accept without fully understanding and agreeing to the method, but I have to agree with tknorris on this, I believe there's a simpler solution that can achieve similar results, and it would be ideal to keep those changes away from the resolvers

I will keep reading thru the PR as I find time

**Comment by VioletRed** [comment] 2015-01-12 20:24
> I think the problem is your changes are too extensive to be all understood and tested at once. Several addons use urlresolver and it would be very bad to break it in unexpected ways.

I understand that part, but you can just ask me if there is something that is not clear.

> In addition, your current PR depends on EVERYONE writing resolvers to know that they need to do them differently now to account for the domain check. To me, that's also a problem.

Seriously, is adding a line like this:
`domains = [ "domain1.com", "domain2.eu" ]`
a big documentation/compatibility problem? Current documentation in interfaces.py
`domains = ['localdomain']`
 `'''(array) List of domains handled by this plugin. Use "*" for universal resolvers.'''  `
should be enough, at least for a competent programer. And if it wasn't, it could be fixed before merging.

> I think the same thing can be achieved more simply by making valid_url a class method and making smaller changes to how the Manager loads the resolvers such that it only instantiates ones that need one of the other methods to be called.

That's what my changes do: don't load unused resolvers, and find possible resolvers in a static way. Sadly, your solution won't provide a big performance improvement because of python internals and current architecture (see below for details).

> Note that in 2012 raspberry devices were running XBMC considerably slower than they do today.

I know, and it still takes 90+ seconds to resolve a URL, so not really "problem solved".

> this isn't a change that I want to accept without fully understanding and agreeing to the method,

Totally reasonable, but you could have asked for an explanation before. Here goes a short explanation of the principles and decisions:

* Speed should be improved in both URLResolver initialization and HostMedia instantiation.
* Plugins using URLResolver should not change (don't touch external API).
* Plugnplay interface shouldn't change for existing resolvers (don't touch internal API). 

There are two bottlenecks in URLResolver performance: 
* Plugin initialization: All resolvers must load and initialize before resolving any url. It imposes a penalty of 5-7 seconds (in rpi) just for writing `import urlresolver`.
* Finding suitable resolvers. It uses regexp and takes 10-12 seconds **for each link**.

The first problem is solved by tweaking the Plugin metaclass. Instead of loading all resolvers, only placeholders are created. If anyone tries to call one of the placeholders a ImportError exception raises and the error handler loads the missing Plugin. This avoids penalizing plugin developers that just import urlresolver (e.g 1channel avoids importing urlresolver until it's time to actually use it, because of how slow it makes everything).

The second problem is the most serious one, and can't be resolved if we call valid_url() method on all resolvers. Changing resolver's methods to class methods (as in the latest plugnplay code and tknorris proposal) produce some minor improvements in speed, more notorious when resolving more than one link. A much important improvement is achieved by not using regex in a first search, but only checking the domains, and calling valid_url() only in a reduced list of possible domains. It reduces the resolving time to less than 2 seconds per link.

The changes make life easier for plugin developers using URLResolver by allowing using a simple 'import' without performance penalty, for users making it way faster, and doesn't impose any serious constrain in resolver developers. Fixing existing resolvers took less than an hour, and fixing new ones takes less than two minutes.

**Comment by tknorris** [comment] 2015-01-12 21:02
Maybe the best thing to do would be to make the changes in an incremental way that we could all understand instead of changes in almost every source file at one time?

Dont' take this the wrong way, but it's easy to be flippant about this when you aren't the one that has to answer all the user's questions when something breaks. I have 2 addons with millions of users that depend on urlresolver, and if urlresolver stopped working all the sudden because of issues with this change I would literally have hundreds of users posting every day about breakage. Keep in mind that urlresolver is hosted in the .org repos so we can't push updates immediately if something breaks.

So, are there ways you can chunk this change up where they don't have to be reviewed all at one time? Maybe solve only the first problem let us all test it throughly and release it and then phase in the 2nd part?

**Comment by Eldorados** [comment] 2015-01-12 21:19
Splitting it out would greatly help me and everyone else who would wish to review!

Appreciate the write up, also provides a ton of help with understanding the changes being done

Don't get us wrong, we all want to speed up urlresolver, 1Channel was forced to put in options specifically due to the lag when loading.  Also my comment earlier was that this issue is becoming more prominent lately and hasn't exactly been a problem for as long as stated, in 2012 the main issue was the lack of optimizations in XBMC for the pi, the growing number of resolvers is dragging urlresolver down now.. we need to turn this around

**Comment by VioletRed** [comment] 2015-01-13 09:31
> Splitting it out would greatly help me and everyone else who would wish to review!

> So, are there ways you can chunk this change up where they don't have to be reviewed all at one time? Maybe solve only the first problem let us all test it throughly and release it and then phase in the 2nd part?

Done in PR #241 

> Dont' take this the wrong way, but it's easy to be flippant about this when you aren't the one that has to answer all the user's questions when something breaks.

I understand that, but I'm more than willing to commit the necessary energy to make it work, I have my own set of users testing this branch since September (friends and relatives that saw my Kodi installation and decided to have their own). Even if the sample is too small for the number of resolvers,  no one has complained yet about broken resolvers, and it makes me hopeful.

**Closed** 2015-01-27 14:25 UTC
